version: "3.0"

services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/src/node_modules

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"

  migration:
    build:
      context: .
    command: ["npm", "run", "migrate"]
    links:
      - db
    depends_on:
      - db

volumes:
  data:
